apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: fastcampus
namePrefix: dev-
nameSuffix: -devops

commonLabels:
  department: "devops"
  owner: "claud"
commonAnnotations:
  key1: "val1"
  key2: "val2"
