context:
  region: "apne2"
  vpc: "apne2-fastcampus"
  cidrs:
    "primary": "10.222.0.0/16"

vpc:
  name: "${vpc}"
  cidr: "${cidrs.primary}"

subnet_groups:
  "public":
    map_public_ip_on_launch: true
    subnets:
    - { cidr: "10.222.0.0/24", az_id: "${region}-az1" }
    - { cidr: "10.222.1.0/24", az_id: "${region}-az2" }
  "private":
    subnets:
    - { cidr: "10.222.2.0/24", az_id: "${region}-az1" }
    - { cidr: "10.222.3.0/24", az_id: "${region}-az2" }
