apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana/
- hello/

replicas:
- name: grafana
  count: 2
- name: hello
  count: 1

images:
- name: grafana/grafana
  newTag: "8.2.2"
- name: nginxdemos/hello
  newName: nginx
  newTag: "latest"
