apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- external-secret.yaml

configMapGenerator:
- name: mysql-config
  literals:
  - MYSQL_DATABASE=devops

namespace: default
